source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

flutter_application_path = '/Users/sgmwh/Desktop/MyChevy/flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'xixixi' do
    pod 'Moya'
    pod 'ReactiveCocoa'
    pod 'HandyJSON'
    pod 'Kingfisher'
    pod 'SwiftyJSON'
    pod 'SnapKit'
    pod 'Toast-Swift'
    pod 'CryptoSwift'
    pod "ESPullToRefresh"
    install_all_flutter_pods(flutter_application_path)
end
